name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - name: Setup .NET 8.x
          uses: actions/setup-dotnet@v3
        - with:
        # Semantic version range syntax or exact version of a dotnet version
            dotnet-version: '8.x'
